### ISSUE TITLE
Publish the website via Github Pages

### ISSUE THREAD

**Issue by michalmikolajczyk** [tksventures/reli-cloud-splashpage#1]
**Is your feature request related to a problem? Please describe.**
Currently, the website `reli.cloud` is not hosted via a platform that we can control. We want to work directly on the code, and be able to publish updates at any time.

**Describe the solution you'd like**
Please export the code from the generator, and deploy using Github Pages.

**Comment by michalmikolajczyk** [comment]
Completed, the website is served via Github Pages
- HTTPS enforced
- all subdomains are redirected to https://reli.cloud

https://reli.cloud/

**Comment by lam3lka** [comment]
Can we count it as LOE 1 @michalmikolajczyk ?
