### ISSUE TITLE
Scrolling prevented on certain mobile devices

### ISSUE THREAD

**Issue by bunthius** [tksventures/reli-cloud-splashpage#14]
**Describe the bug**
User in slack reports reli.cloud scrolling is prevented on Samsung S6. This can also be demonstrated in google chrome device simulator.

**To Reproduce**
1. Go to chrome device simulator
2. Click on drop down to select galaxy s5 or other mobile devices
3. attempt to scroll down

**Expected behavior**
Normal webpage scrolling.

**Screenshots**
https://www.loom.com/share/3947355ba6eb4cf0aec4a43b93ab7c48

**Desktop (please complete the following information):**
 - OS: windows 10
 - Browser chrome

**Smartphone (please complete the following information):**
 - Device: Samsung S6

**Additional context**
general-internal & bugs channel in slack for connecting with user.

**Comment by lam3lka** [comment]
@MikeLuDev what is the LOE of this issue?

**Comment by MikeLuDev** [comment]
Added `LOE1` tag to reflect actual work done.
