### ISSUE TITLE
Unhide the contact form and make functional

### ISSUE THREAD

**Issue by bunthius** [tksventures/reli-cloud-splashpage#15]
## **Is your feature request related to a problem? Please describe.**
Originally, a contact form was designed but removed from launch. We discussed bringing it back and making it functional.

## **Describe the solution you'd like**
The code should still be in the repo as they were exported from webflow but are hidden. See the image pasted at the bottom of this description to view more details for what needs to be unhidden and refined. (note, there are some complications with browsers overriding the styles and these need to be overwritten for all browsers)

Here are links to the xd links. 
Prototype:
https://xd.adobe.com/view/c0eebf82-0bac-4ba1-7bd1-384df982a398-b6df/

Design Specs:
https://xd.adobe.com/spec/45c146a4-878c-4eab-5d6b-50e883637d14-33f0/

XD File:
https://1drv.ms/u/s!AnYXMNVyyfNxjdoNErWlbaucGCPS9g

@eugenelopin can you provide additional details on what categories of subject lines should be added into the dropdown of "Select Reason for Contact" and add them into this issue.

## **Describe alternatives you've considered**
Google Forms? Keep the email link only.

## **Additional context**
Screenshot from webflow showing the classes that need to be visible and should still be in code. The names of the classes are on the left panel.
![image](https://user-images.githubusercontent.com/6615043/58362445-0740e180-7e65-11e9-9b2c-aeaaa49c2686.png)

**Comment by michalmikolajczyk** [comment]
Can we add the form with the new Vue Storefront shop?
