### ISSUE TITLE
Need to select reli contact email easily from landing page form

### ISSUE THREAD

**Issue by bunthius** [tksventures/reli-cloud-splashpage#23]
**Describe the bug**
There's only a small area that allows for selecting the email due to other elements above it in the z-index. Also contact@reli.cloud email can be a link to open default mail client.

**To Reproduce**
1. Go to reli.cloud
2. Click on contact button
3. Scroll down to email section with contact@reli.cloud email text label
4. Try to select the email text from all angles to see how it's not easy to select it for clipboard copying.

**Expected behavior**
- [ ] Easy to select text to copy to clipboard 
- [ ] Click to open default mail client.

**Screenshots**
Image below shows the elements on top of the text that don't allows selecting.
![image.png](https://images.zenhubusercontent.com/5c128a7da43e9647e63a8de1/80dba163-7fd7-43a6-8442-c9a46f7a7b39)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Chrome
 - Version latest

**Comment by bunthius** [comment]
@Masziooo regarding bugs, when they are completed please set a label as LOE 1,2, etc. based on how long the issue took to close. Also, set the Estimate to the same number using zenhub. You can do this after issues are closed. I set this one to loe 1 so just for future reference. Thanks, and very nice work on this!

Also, please check off items in the initial description.

**Comment by Masziooo** [comment]
OK, I'll remember. Thanks!
