### ISSUE TITLE
Redo Hero Section & Create Products Section

### ISSUE THREAD

**Issue by bunthius** [tksventures/reli-cloud-splashpage#25]
# Problem
We need to integrate the landing page with the vue storefront reli.cloud app. 

# Solution
- [ ] Integrate new xd prototype design into vue storefront pwa app
- [ ] Redo the hero section to the new xd prototype below
- [ ] Include an account creation CTA in the hero section
- [ ] Add a products section allowing users to quickly add cluster packages into their cart to pay for them
- [ ] 1/4 cluster premium product option is default highlighted, but hovering over other product items highlights them such as seen on page 2 of the xd prototype below

# XD Links
Raw XD File: https://1drv.ms/u/s!AnYXMNVyyfNxlY50MWaTqR4jFFWAXQ?e=U9Q71x
XD Prototype: https://xd.adobe.com/view/11e3aafb-a9f2-4086-79a2-4f81dd45f3de-67d2/
XD Development Specs: https://xd.adobe.com/view/11e3aafb-a9f2-4086-79a2-4f81dd45f3de-67d2/ (click the </> icon)

**Comment by michalmikolajczyk** [comment]
closing in favor of: https://github.com/tksventures/reli/issues/30
