### ISSUE TITLE
Adwords campaign

### ISSUE THREAD

**Issue by michalmikolajczyk** [tksventures/reli-cloud-splashpage#26]
**Is your feature request related to a problem? Please describe.**
We want to start working with real users on our Reli platform.

**Describe the solution you'd like**
Set up adwords campaign for managed Kubernetes. It's best if the campaign could further navigate us at the keywords - we can use a few different versions of the ad.

**Additional context**
Please check the app at https://kwfinder.com/ to find additional keywords (there's a free trial). 

We have not previously used google ads I believe, so we may be eligible for some first-time offers and get help from a professional at Google.

<img width="1680" alt="Screen Shot 2020-02-10 at 12 22 32 PM" src="https://user-images.githubusercontent.com/1655227/74146197-e4c44380-4c00-11ea-970e-31fc3a498d36.png">

**Comment by bunthius** [comment]
@tksventures/engineers please chime in if you have suggestions on which type of ad words to test out.

**Comment by Gallred** [comment]
Ad campaign submitted as of Feb 11, 1:40 PM.

Initial keyword set using kwfinder pointed us to the following.  @bravetarget - per discussion with Mike we decided to include one AWS keyword.

kubernetes
kubernetes aws
kubernetes docker
managed kubernetes
grafana
docker and kubernetes
docker kubernetes
docker orchestration
kubernetes cloud provider
kubernetes cloud
kubernetes google cloud
kubernetes hosting
kubernetes load balancer

Starting with the following country set...

Canada
China
France
Germany
India
Japan
Poland
Russia
Ukraine
United Kingdom
United States

Will refine as we see CTR and leads generate...
