### ISSUE TITLE
Images / design updates

### ISSUE THREAD

**Issue by michalmikolajczyk** [tksventures/reli-cloud-splashpage#3]
**Is your feature request related to a problem? Please describe.**
We need to make some updates to the website, in terms of the images used.

**Describe the solution you'd like**
A list of suggested changes:

- [x] remove fog / transparency from images replace with product images in style of google webstore best practices.
- [x] remove the "lego figure" characters replace with smaller products CTA midpage

Anything else?

@tksventures/engineers @tksventures/product-owners @tksventures/project-managers

**Comment by bunthius** [comment]
Follow up issue at #25
